name: Deploy to PythonAnywhere (Individual Pull)

# Trigger the workflow on push to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Deploy to PythonAnywhere
      run: |
        python individualPullToPAW.py
      env:
        PAW_USERNAME: ${{ secrets.PAW_USERNAME }}
        PAW_TOKEN: ${{ secrets.PAW_TOKEN }}
        PAW_HOST: ${{ secrets.PAW_HOST }}
        PAW_CLI: ${{ secrets.PAW_CLI }}
        PAW_PROJECT_PATH: ${{ secrets.PAW_PROJECT_PATH }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    
    - name: Display deployment result
      run: |
        echo "Deployment workflow completed!"
        echo "Check the logs above for deployment status."